### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by somenxavier** [cebe/js-search#5]
I get this:
```
$ composer require "cebe/js-search"
PHP Fatal error:  Class 'Phar' not found in /usr/bin/composer on line 23
```

**Comment by cebe** [comment]
quite sure this is not related to this package. which version of composer are you using and which PHP version?

**Comment by cebe** [comment]
You are missing the php phar extensions, see e.g. http://stackoverflow.com/questions/17633784/xampp-composer-php-fatal-error-class-phar-not-found or google the error message for more details.

**Comment by somenxavier** [comment]
thanks
