### ISSUE TITLE
vendor/bin/jsindex <path-to-your-html-files>

### ISSUE THREAD

**Issue by nexjsystems** [cebe/js-search#8]
Getting 'vendor' is not recognized as an internal or external command,
operable program or batch file.

Can you please specify what the **exact** syntax is for <path-to-your-html-files> after vendor/bin/jsindex please. I am trying to run this off a folder on my desktop. First function ran fine.

**Comment by nztim** [comment]
When installing via Composer, the path to the executable will usually be `vendor/bin/jsindex`. 
If you have just downloaded the zip package then it will be `bin/jsindex`
It's a PHP file so you can run it like with `php vendor/bin/jsindex` or `php bin/jsindex`.

Here's a quick way to see the example code work in a folder on your desktop:
Download this package as a zip file, unzip to a folder, then inside the folder:

```
composer install
php bin/jsindex tests/data
```
Open `example.html` in a browser and type "head" and you should see a result appear.

**Comment by nexjsystems** [comment]
Hey, thanks for the response! 

Everything is working fine, believe it or not I had to change the forward slashes to back slashes. 

vendor/bin/jsindex <path-to-your-html-files>

to

vendor\bin\jsindex <path-to-your-html-files>

and it worked perfectly!
